version: '3.8'

networks:
  monitoring:
    driver: bridge
    name: monitoring_network

services:
  nginx:
    image: nginx:latest
    container_name: monitor_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - monitoring
    ports:
      - 3001:81
    depends_on:
      - grafana
      - prometheus
      - alertmanager
      - node-exporter
      - cadvisor

  prometheus:
    image: prom/prometheus
    user: "1000"
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/:/etc/config/
      - ./storage/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - node-exporter
      - cadvisor
    links:
      - alertmanager
      - node-exporter
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/alertmanager.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitoring
    ports:
      - 127.0.0.1:9093:9093

  grafana:
    image: grafana/grafana:11.2.0
    user: "1000"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
      - ./storage/grafana-data:/var/lib/grafana
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.8.2
    ports:
      - "127.0.0.1:9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring

  blackbox:
    image: prom/blackbox-exporter:v0.16.0
    container_name: blackbox
    restart: unless-stopped
    volumes:
      - ./etc/blackbox.yml:/etc/blackbox/blackbox.yml
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    networks:
      - monitoring
    ports:
      - 127.0.0.1:9115:9115
